### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by dfrencham** [ifreecarve/arduino_ci#30]
## System

- URL of failing Travis CI job: https://travis-ci.org/dfrencham/rad-gate
- URL of your Arduino project: https://github.com/dfrencham/rad-gate/tree/unittest

## Issue  Summary

Locally (in OSX) and remotely the following error is displayed when running unit tests:

```
/home/travis/.rvm/gems/ruby-2.4.1/gems/arduino_ci-0.1.8/lib/arduino_ci/cpp_library.rb:185:in 
`build_for_test_with_configuration': wrong number of arguments (given 3, expected 4) (ArgumentError)
```

The broken code seems to be in `arduino_ci_remote.rb`

This line is missing a parameter:

```
exe = cpp_library.build_for_test_with_configuration(
            unittest_path,
            config.aux_libraries_for_unittest,
            config.gcc_config(p)
          )
```

It should be

```
exe = cpp_library.build_for_test_with_configuration(
            unittest_path,
            config.aux_libraries_for_unittest,
            gcc_binary,
            config.gcc_config(p)
          )
```

**Comment by ifreecarve** [comment]
Well that's embarrassing.  Although I'm digging now to find out how/why [that slipped through this CI job](https://travis-ci.org/ifreecarve/arduino_ci/builds/361220344), since I run `arduino_ci_remote.rb` as part of that process...
